# Development values - Auth Bypass Mode
# Use with: helm install -f values-dev-noauth.yaml

# Override secrets for development with auth bypass
secrets:
  ENVIRONMENT: "development"
  DEBUG: "true"
  BYPASS_AUTH: "true"
  
  # Database (can use simple passwords in dev)
  POSTGRES_DB: "spending-monitor"
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "devpassword"
  DATABASE_URL: "postgresql+asyncpg://user:devpassword@spending-monitor-db:5432/spending-monitor"
  
  # LLM Configuration (use test keys)
  LLM_PROVIDER: "openai"
  BASE_URL: "https://api.openai.com/v1"
  API_KEY: "test-key-replace-me"
  MODEL: "gpt-3.5-turbo"
  
  # CORS - allow all in dev
  CORS_ALLOWED_ORIGINS: "*"
  ALLOWED_ORIGINS: "*"
  
  # SMTP - use dummy values
  SMTP_HOST: "smtp.example.com"
  SMTP_PORT: "587"
  SMTP_FROM_EMAIL: "dev@localhost"
  SMTP_USE_TLS: "false"
  SMTP_USE_SSL: "false"
  
  # Keycloak - not used in bypass mode but required by schema
  KEYCLOAK_URL: "http://localhost:8080"
  KEYCLOAK_REALM: "spending-monitor"
  KEYCLOAK_CLIENT_ID: "spending-monitor"
  
  # UI
  VITE_API_BASE_URL: "/api"

# Reduced resources for dev
api:
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

ui:
  replicas: 1
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# No persistence in dev
database:
  persistence:
    enabled: false
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# Increase migration resources (we saw OOM issues)
migration:
  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "500m"

