{{- if .Values.keycloak.enabled }}
---
# ClusterRole for preflight check - needs to list CRDs
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "spending-monitor.fullname" . }}-preflight
  labels:
    app.kubernetes.io/name: {{ include "spending-monitor.name" . }}
    app.kubernetes.io/component: keycloak-preflight
    app.kubernetes.io/part-of: {{ .Chart.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

---
# ClusterRoleBinding for preflight check
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "spending-monitor.fullname" . }}-preflight
  labels:
    app.kubernetes.io/name: {{ include "spending-monitor.name" . }}
    app.kubernetes.io/component: keycloak-preflight
    app.kubernetes.io/part-of: {{ .Chart.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "spending-monitor.fullname" . }}-preflight
subjects:
  - kind: ServiceAccount
    name: {{ include "spending-monitor.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}

