---
# OpenShift BuildConfigs and ImageStreams
# This file creates BuildConfigs that build images directly in OpenShift
# Usage: 
#   1. Update GIT_URI and GIT_REF as needed
#   2. Apply: oc apply -f openshift-builds-template.yaml -n <namespace>
#   3. Start builds: oc start-build <buildconfig-name> -n <namespace>

# =============================================================================
# API Service
# =============================================================================

apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: spending-monitor-api
  labels:
    app: spending-monitor
    component: api

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: spending-monitor-api
  labels:
    app: spending-monitor
    component: api
spec:
  output:
    to:
      kind: ImageStreamTag
      name: spending-monitor-api:latest
  source:
    type: Git
    git:
      uri: ${GIT_URI}
      ref: ${GIT_REF}
    contextDir: .
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: packages/api/Containerfile
  resources:
    limits:
      memory: 4Gi
      cpu: "2"
    requests:
      memory: 2Gi
      cpu: "1"

---
# =============================================================================
# UI Service
# =============================================================================

apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: spending-monitor-ui
  labels:
    app: spending-monitor
    component: ui

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: spending-monitor-ui
  labels:
    app: spending-monitor
    component: ui
spec:
  output:
    to:
      kind: ImageStreamTag
      name: spending-monitor-ui:latest
  source:
    type: Git
    git:
      uri: ${GIT_URI}
      ref: ${GIT_REF}
    contextDir: .
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: packages/ui/Containerfile
      buildArgs:
        - name: VITE_BYPASS_AUTH
          value: "${VITE_BYPASS_AUTH}"
        - name: VITE_API_BASE_URL
          value: "/api"
        - name: VITE_ENVIRONMENT
          value: "${VITE_ENVIRONMENT}"
  resources:
    limits:
      memory: 4Gi
      cpu: "2"
    requests:
      memory: 2Gi
      cpu: "1"

---
# =============================================================================
# Database Service
# =============================================================================

apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: spending-monitor-db
  labels:
    app: spending-monitor
    component: database

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: spending-monitor-db
  labels:
    app: spending-monitor
    component: database
spec:
  output:
    to:
      kind: ImageStreamTag
      name: spending-monitor-db:latest
  source:
    type: Git
    git:
      uri: ${GIT_URI}
      ref: ${GIT_REF}
    contextDir: .
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: packages/db/Containerfile
  resources:
    limits:
      memory: 2Gi
      cpu: "1"
    requests:
      memory: 1Gi
      cpu: 500m


